package com.nest5.businessClient;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.nest5.businessClient.DailySaleDao;
import com.nest5.businessClient.ImpuestoDao;
import com.nest5.businessClient.IngredienteDao;
import com.nest5.businessClient.ProductoDao;
import com.nest5.businessClient.CombinacionDao;
import com.nest5.businessClient.SaleIngredienteDao;
import com.nest5.businessClient.SaleProductoDao;
import com.nest5.businessClient.SaleCombinacionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1000): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1000;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        DailySaleDao.createTable(db, ifNotExists);
        ImpuestoDao.createTable(db, ifNotExists);
        IngredienteDao.createTable(db, ifNotExists);
        ProductoDao.createTable(db, ifNotExists);
        CombinacionDao.createTable(db, ifNotExists);
        SaleIngredienteDao.createTable(db, ifNotExists);
        SaleProductoDao.createTable(db, ifNotExists);
        SaleCombinacionDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        DailySaleDao.dropTable(db, ifExists);
        ImpuestoDao.dropTable(db, ifExists);
        IngredienteDao.dropTable(db, ifExists);
        ProductoDao.dropTable(db, ifExists);
        CombinacionDao.dropTable(db, ifExists);
        SaleIngredienteDao.dropTable(db, ifExists);
        SaleProductoDao.dropTable(db, ifExists);
        SaleCombinacionDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(DailySaleDao.class);
        registerDaoClass(ImpuestoDao.class);
        registerDaoClass(IngredienteDao.class);
        registerDaoClass(ProductoDao.class);
        registerDaoClass(CombinacionDao.class);
        registerDaoClass(SaleIngredienteDao.class);
        registerDaoClass(SaleProductoDao.class);
        registerDaoClass(SaleCombinacionDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
