package com.nest5.businessClient;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IMPUESTO.
 */
public class Impuesto {

    private long id;
    private long syncId;
    private double percentage;
    /** Not-null value. */
    private String name;

    public Impuesto() {
    }

    public Impuesto(long id) {
        this.id = id;
    }

    public Impuesto(long id, long syncId, double percentage, String name) {
        this.id = id;
        this.syncId = syncId;
        this.percentage = percentage;
        this.name = name;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getSyncId() {
        return syncId;
    }

    public void setSyncId(long syncId) {
        this.syncId = syncId;
    }

    public double getPercentage() {
        return percentage;
    }

    public void setPercentage(double percentage) {
        this.percentage = percentage;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

}
