package com.nest5.businessClient;

import com.nest5.businessClient.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SALE_COMBINACION.
 */
public class SaleCombinacion {

    private Integer quantity;
    private Long saleId;
    private Long combinacionId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SaleCombinacionDao myDao;

    private DailySale dailySale;
    private Long dailySale__resolvedKey;

    private Combinacion combinacion;
    private Long combinacion__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SaleCombinacion() {
    }

    public SaleCombinacion(Integer quantity, Long saleId, Long combinacionId) {
        this.quantity = quantity;
        this.saleId = saleId;
        this.combinacionId = combinacionId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSaleCombinacionDao() : null;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Long getSaleId() {
        return saleId;
    }

    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    public Long getCombinacionId() {
        return combinacionId;
    }

    public void setCombinacionId(Long combinacionId) {
        this.combinacionId = combinacionId;
    }

    /** To-one relationship, resolved on first access. */
    public DailySale getDailySale() {
        Long __key = this.saleId;
        if (dailySale__resolvedKey == null || !dailySale__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DailySaleDao targetDao = daoSession.getDailySaleDao();
            DailySale dailySaleNew = targetDao.load(__key);
            synchronized (this) {
                dailySale = dailySaleNew;
            	dailySale__resolvedKey = __key;
            }
        }
        return dailySale;
    }

    public void setDailySale(DailySale dailySale) {
        synchronized (this) {
            this.dailySale = dailySale;
            saleId = dailySale == null ? null : dailySale.getId();
            dailySale__resolvedKey = saleId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Combinacion getCombinacion() {
        Long __key = this.combinacionId;
        if (combinacion__resolvedKey == null || !combinacion__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CombinacionDao targetDao = daoSession.getCombinacionDao();
            Combinacion combinacionNew = targetDao.load(__key);
            synchronized (this) {
                combinacion = combinacionNew;
            	combinacion__resolvedKey = __key;
            }
        }
        return combinacion;
    }

    public void setCombinacion(Combinacion combinacion) {
        synchronized (this) {
            this.combinacion = combinacion;
            combinacionId = combinacion == null ? null : combinacion.getId();
            combinacion__resolvedKey = combinacionId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
