package com.nest5.businessClient;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.nest5.businessClient.SaleCombinacion;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SALE_COMBINACION.
*/
public class SaleCombinacionDao extends AbstractDao<SaleCombinacion, Void> {

    public static final String TABLENAME = "SALE_COMBINACION";

    /**
     * Properties of entity SaleCombinacion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Quantity = new Property(0, Integer.class, "quantity", false, "QUANTITY");
        public final static Property SaleId = new Property(1, Long.class, "saleId", false, "SALE_ID");
        public final static Property CombinacionId = new Property(2, Long.class, "combinacionId", false, "COMBINACION_ID");
    };

    private DaoSession daoSession;

    private Query<SaleCombinacion> dailySale_CombosQuery;

    public SaleCombinacionDao(DaoConfig config) {
        super(config);
    }
    
    public SaleCombinacionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SALE_COMBINACION' (" + //
                "'QUANTITY' INTEGER," + // 0: quantity
                "'SALE_ID' INTEGER," + // 1: saleId
                "'COMBINACION_ID' INTEGER);"); // 2: combinacionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SALE_COMBINACION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SaleCombinacion entity) {
        stmt.clearBindings();
 
        Integer quantity = entity.getQuantity();
        if (quantity != null) {
            stmt.bindLong(1, quantity);
        }
 
        Long saleId = entity.getSaleId();
        if (saleId != null) {
            stmt.bindLong(2, saleId);
        }
 
        Long combinacionId = entity.getCombinacionId();
        if (combinacionId != null) {
            stmt.bindLong(3, combinacionId);
        }
    }

    @Override
    protected void attachEntity(SaleCombinacion entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public SaleCombinacion readEntity(Cursor cursor, int offset) {
        SaleCombinacion entity = new SaleCombinacion( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // quantity
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // saleId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // combinacionId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SaleCombinacion entity, int offset) {
        entity.setQuantity(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setSaleId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCombinacionId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(SaleCombinacion entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(SaleCombinacion entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "combos" to-many relationship of DailySale. */
    public List<SaleCombinacion> _queryDailySale_Combos(Long combinacionId) {
        synchronized (this) {
            if (dailySale_CombosQuery == null) {
                QueryBuilder<SaleCombinacion> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CombinacionId.eq(null));
                dailySale_CombosQuery = queryBuilder.build();
            }
        }
        Query<SaleCombinacion> query = dailySale_CombosQuery.forCurrentThread();
        query.setParameter(0, combinacionId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDailySaleDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getCombinacionDao().getAllColumns());
            builder.append(" FROM SALE_COMBINACION T");
            builder.append(" LEFT JOIN DAILY_SALE T0 ON T.'SALE_ID'=T0.'_id'");
            builder.append(" LEFT JOIN COMBINACION T1 ON T.'COMBINACION_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected SaleCombinacion loadCurrentDeep(Cursor cursor, boolean lock) {
        SaleCombinacion entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DailySale dailySale = loadCurrentOther(daoSession.getDailySaleDao(), cursor, offset);
        entity.setDailySale(dailySale);
        offset += daoSession.getDailySaleDao().getAllColumns().length;

        Combinacion combinacion = loadCurrentOther(daoSession.getCombinacionDao(), cursor, offset);
        entity.setCombinacion(combinacion);

        return entity;    
    }

    public SaleCombinacion loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<SaleCombinacion> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<SaleCombinacion> list = new ArrayList<SaleCombinacion>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<SaleCombinacion> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<SaleCombinacion> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
